from django.db import models
from django.utils import timezone


class LogEntry(models.Model):
    """Raw log entries ingested from various sources"""
    
    SOURCE_CHOICES = [
        ('webserver', 'Web Server'),
        ('firewall', 'Firewall'),
        ('ssh', 'SSH Auth'),
        ('ids', 'Intrusion Detection System'),
        ('custom', 'Custom'),
    ]
    
    timestamp = models.DateTimeField(default=timezone.now)
    source_type = models.CharField(max_length=20, choices=SOURCE_CHOICES)
    source_ip = models.GenericIPAddressField(null=True, blank=True)
    destination_ip = models.GenericIPAddressField(null=True, blank=True)
    destination_port = models.IntegerField(null=True, blank=True)
    action = models.CharField(max_length=100)  # e.g., "LOGIN_FAILED", "GET /admin"
    raw_log = models.TextField()  # The original log line
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-timestamp']
    
    def __str__(self):
        return f"[{self.timestamp}] {self.source_type} - {self.source_ip} - {self.action}"


class Alert(models.Model):
    """Security alerts generated by our detection engine"""
    
    SEVERITY_CHOICES = [
        ('CRITICAL', 'Critical'),
        ('HIGH', 'High'),
        ('MEDIUM', 'Medium'),
        ('LOW', 'Low'),
        ('INFO', 'Informational'),
    ]
    
    STATUS_CHOICES = [
        ('NEW', 'New'),
        ('INVESTIGATING', 'Investigating'),
        ('RESOLVED', 'Resolved'),
        ('FALSE_POSITIVE', 'False Positive'),
    ]
    
    title = models.CharField(max_length=200)
    description = models.TextField()
    severity = models.CharField(max_length=10, choices=SEVERITY_CHOICES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='NEW')
    source_ip = models.GenericIPAddressField(null=True, blank=True)
    rule_name = models.CharField(max_length=100)  # Which detection rule triggered this
    mitre_tactic = models.CharField(max_length=100, blank=True)  # MITRE ATT&CK tactic
    mitre_technique = models.CharField(max_length=100, blank=True)  # e.g., T1110
    evidence = models.TextField(blank=True)  # Related log entries as proof
    timestamp = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-timestamp']
    
    def __str__(self):
        return f"[{self.severity}] {self.title} - {self.source_ip}"


class DetectionRule(models.Model):
    """Track our detection rules"""
    
    name = models.CharField(max_length=100)
    description = models.TextField()
    severity = models.CharField(max_length=10, choices=Alert.SEVERITY_CHOICES)
    mitre_tactic = models.CharField(max_length=100, blank=True)
    mitre_technique = models.CharField(max_length=100, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.name} ({self.severity})"